[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/military-entities"
  to = "/.netlify/functions/military-entities"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions" 